packer {
  required_plugins {
    azure = {
      version = ">= 2.0.0"
      source  = "github.com/hashicorp/azure"
    }
  }
}


source "azure-arm" "autogenerated_1" {

  use_azure_cli_auth = true
  azure_tags = {
    dept = "Engineering"
    task = "Image deployment"
  }

  image_offer     = "0001-com-ubuntu-server-jammy"
  image_publisher = "canonical"
  image_sku       = "22_04-lts"
  location        = "centralus"

  managed_image_name                = "myPackerImage"
  managed_image_resource_group_name = "packer-rg"

  os_type         = "Linux"
  subscription_id = "a452fff0-1433-47fa-b372-cd76c8bece23"
  vm_size         = "Standard_D2s_v3"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]
}